### PR TITLE
EOL KDE 5.10

### PR DESCRIPTION
**Pull request by ramcq**
https://github.com/flathub/buildbot-config/issues/48

### CODE REVIEW

**Comment by tsdgeos** [comment]
Ping, can we get this merged? 

@ramcq @barthalion

**Comment by barthalion** [comment]
I plan to mark 1.6 and 18.08 as EOL this week. I will add 5.10 to the list.

**Comment by tsdgeos** [comment]
> I plan to mark 1.6 and 18.08 as EOL this week. I will add 5.10 to the list.

Actually i was talking with Aleix and we'd want to mark 5.10, 5.11 and 5.13 to the EOL list, if you can handle that it'd be great :)

**Comment by tsdgeos** [comment]
@barthalion did you have time to pick this up?

**Comment by tsdgeos** [comment]
@barthalion Ping?

**Comment by barthalion** [comment]
I have marked as EOL 5.10, 5.11 and 5.13, but also 5.9, as it's based on freedesktop runtime 1.6 which had no updates for 2 years now. Also dropped them from the config file.

**Pull request closed without merging**
